### ISSUE TITLE
Use Ann-Kathrin's research as mantik showcase

### ISSUE THREAD

**Issue by thomose** [mantik-ai/tutorials#10]
## Problem to solve

As mantik user I want to have a gallery of projects showcasing the platform, so that I can get an immediate idea of the platform's capabilities.

## Details

This story is only workable iff permission was granted in #5.

## Proposal

 - [x] Collect code dependencies in a `requirements.txt` file
 - [x] Create Dockerfile or apptainer recipe to install the project into a container
 - [x] Write entrypoint scripts and the corresponding `mlproject` file
 - [x] Include mlflow tracking to mantik into the scripts
 - [x] Create an experiment on `cloud.mantik.ai`
 - [x] Run the project on JUWELS and track to `cloud.mantik.ai`
 - [x] Write a README with a project description and citations of papers etc.

## Acceptance

 - [x] Project can be built and run
 - [x] Results are tracked to mantik
 - [x] README contains links to publications, original repo (if possible) and explicitly names Ann-Kathrin as original author of the code

**Comment by Angie25** [comment]
- The code base is available in gitlab.com and not public.
- A small dataset is used to run the code, no GPUs are necessary.
- The code can run with tracking enabled.

**Comment by Angie25** [comment]
README sample

Integrating ML-Hazard Mapping into the AI-platform

This project sets up a workflow for investigating mountain slopes for their likelihood of the occurrence of shallow landslide-type slope failures using an decision tree-based ML model. This work has mainly been conducted locally without the Juwels resources. Through the AI-platform it is possible to manage the training workflows and also to track the experiments and their results.

**Comment by thomose** [comment]
Note: README is short because no more information was given.
