### ISSUE TITLE
External review of tutorials 

### ISSUE THREAD

**Issue by thomose** [mantik-ai/tutorials#4]
## Problem to solve

As an ML researcher I want a complete and usable tutorial to get me started with mantik.

## Details

@Angie25 will do an external review of the tutorial.

## Proposal

 - [x] Read all materials
 - [x] Execute the demo and all other instructions
 - [x] Note all errors and unclarities in a Pull Request
 - [x] one of the maintainers fixes all comments

## Acceptance

 - [x] Tutorials and demo can be executed and understood by external users

**Comment by Angie25** [comment]
- Registration into the platform

In the tutorial, it is mentioned to contact the platform admins for the registration into platform. Registration, invitation for login to the platform have to be checked (it takes 30 minutes to receive the email with the credentials). 

- Structure of the tutorial
  
Give only general information on the entry page without instructing how to run the code or merge the Quickstart in the entry page and the Mantik Demo. (Issue that came out: in the main tutorial there is no specification that the singularity container should be created to run the code, but there are instructions on how to run some code snippet).

- Other details

To be checked: the necessary format for mlproject_path. 

Is exp_id a string, integer? What is its meaning/usage, how to set it?
 
(Not very clear why/when to use mantik cli, very few details given.)

**Comment by Angie25** [comment]
- In Mantik Demo/ Setup environment, add the info that the environment variables can be already found under environment.sh.

**Comment by Angie25** [comment]
- Not clear the relationship and roles between Dockerfile, MLproject, recipe.def files in "tutorials/demos/wine-quality-estimator/mlproject/". When are Dockerfile and MLproject files actually used? When do we use the singularity images and when do we use the docker images?

**Comment by thomose** [comment]
Describe best practices regarding data (do not bake it into images!)

**Comment by Angie25** [comment]
Comments about the recent commits:
- Commit: Be more clear about experiment IDs
Original text: Experiment IDs are integers that can be 
obtained from the user interface. </br>
Comment: Can we obtain them from the UI? I am not sure what 'obtain' means in this case. I think we can just see them from the UI based on how we set them previously - they are used to categorize different experiments in different groups based on how we set them from the environment variable. I am not completely sure if "obtain" is the right term.

- Commit: Add data best practices
We recommend not to build data directly into Singularity / Apptainer images and ideally store them directly on the remote system and just reference the according path in your code. </br> 
Comment: Maybe you could add that the path can also be passed when running the apptainer?

**Comment by thomose** [comment]
@Angie25 I updated the documentation according to your comments
