### ISSUE TITLE
Contact KISTE PhDs

### ISSUE THREAD

**Issue by thomose** [mantik-ai/tutorials#5]
## Problem to solve

As mantik user I want to have a gallery of projects that the platform was used for, so that I can get an immediate idea of the platform's capabilities.

## Details

The research projects of the five KISTE PhDs will serve as case studies for mantik platform usage.

This story is about communication with KISTE PhDs and thus might have to be handled asynchronously. 

## Proposal

 - [x] Find out whether we need written permission or any kind of software license for the showcase
 - [x] Ask for access to the research code of:
   - [x]  Ankit
   - [x] Kaveh
   - [x] DC
   - [x] Timo
   - [x] Ann-Kathrin

## Acceptance

 - [x] Code can be accessed
 - [x] ~~Permission to use the code as part of the mantik showcase is granted~~

**Comment by thomose** [comment]
Note: KISTE PhDs are (in part) hesitant with granting blanco permissions. We will revisit those as soon as the concept for showcasing the projects is finalized in a separate issue.

**Comment by Angie25** [comment]
- All the PhDs have been contacted and there is access to the code of 4 out of 5 PhD projects. 
- Kaveh's code is only available in scattered Jupyter Notebooks at the moment. It might take some weeks until he organizes the code in a repository.
