### ISSUE TITLE
Use DC's research as mantik showcase

### ISSUE THREAD

**Issue by thomose** [mantik-ai/tutorials#9]
## Problem to solve

As mantik user I want to have a gallery of projects showcasing the platform, so that I can get an immediate idea of the platform's capabilities.

## Details

This story is only workable iff permission was granted in #5.

## Proposal

 - [ ] Collect code dependencies in a `requirements.txt` file
 - [ ] Create Dockerfile or apptainer recipe to install the project into a container
 - [ ] Write entrypoint scripts and the corresponding `mlproject` file
 - [ ] Include mlflow tracking to mantik into the scripts
 - [ ] Create an experiment on `dev.cloud.mantik.ai`
 - [ ] Run the project on JUWELS and track to `dev.cloud.mantik.ai`
 - [ ] Write a README with a project description and citations of papers etc.

## Acceptance

 - [ ] Project can be built and run
 - [ ] Results are tracked to mantik
 - [ ] README contains links to publications, original repo (if possible) and explicitly names DC as original author of the code

**Comment by Angie25** [comment]
- The code base is available, but the work for the models is not over yet. It is work in progress for DC.
- Vissl library is being used for machine learning pipeline. Need to figure out how to integrate mlflow tracking to vissl library.

**Comment by thomose** [comment]
There's still issues running the code. We will try once more, otherwise closing.
